// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckInDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("check_in_date");

                    b.Property<string>("CheckOutDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("check_out_date");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double")
                        .HasColumnName("total_price");

                    b.Property<string>("UpdatedAt")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = "2026-08-20",
                            CheckOutDate = "2026-08-23",
                            CreatedAt = "2026-08-15 10:00:00",
                            CustomerId = 1,
                            RoomId = 1,
                            Status = "confirmed",
                            TotalPrice = 5670000.0
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = "2026-08-15",
                            CheckOutDate = "2026-08-18",
                            CreatedAt = "2026-08-10 14:30:00",
                            CustomerId = 2,
                            RoomId = 4,
                            Status = "occupied",
                            TotalPrice = 8250000.0
                        },
                        new
                        {
                            Id = 3,
                            CheckInDate = "2026-09-01",
                            CheckOutDate = "2026-09-05",
                            CreatedAt = "2026-08-12 09:00:00",
                            CustomerId = 3,
                            RoomId = 5,
                            Status = "pending",
                            TotalPrice = 16800000.0
                        });
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("IdCard")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id_card");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "TP.HCM",
                            CreatedAt = "2026-01-15 10:00:00",
                            Email = "nguyenvana@gmail.com",
                            IdCard = "079123456789",
                            Name = "Nguyễn Văn A",
                            Phone = "0901234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Nội",
                            CreatedAt = "2026-02-20 14:30:00",
                            Email = "tranthib@gmail.com",
                            IdCard = "079987654321",
                            Name = "Trần Thị B",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Đà Nẵng",
                            CreatedAt = "2026-03-10 09:15:00",
                            Email = "levanc@gmail.com",
                            IdCard = "079111222333",
                            Name = "Lê Văn C",
                            Phone = "0923456789"
                        });
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("created_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<string>("PaidAt")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("transaction_code");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000000.0,
                            BookingId = 1,
                            CreatedAt = "2026-08-15 10:05:00",
                            Method = "bank_transfer",
                            Notes = "Đặt cọc giữ phòng",
                            PaidAt = "2026-08-15 10:06:00",
                            Status = "completed",
                            TransactionCode = "PAY-20260815-0001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8250000.0,
                            BookingId = 2,
                            CreatedAt = "2026-08-10 14:35:00",
                            Method = "cash",
                            Notes = "Thanh toán đủ tại quầy",
                            PaidAt = "2026-08-10 14:40:00",
                            Status = "completed",
                            TransactionCode = "PAY-20260810-0002"
                        });
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("room_number");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Description = "Tone trắng và gỗ sồi; cửa sổ nhìn ra vườn zen nội khu.",
                            Price = 1890000.0,
                            RoomNumber = "801",
                            RoomTypeId = 1,
                            Status = "available"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Description = "Giường queen, chăn duvet cotton organic.",
                            Price = 1950000.0,
                            RoomNumber = "802",
                            RoomTypeId = 1,
                            Status = "available"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            Description = "Không gian chia vùng sống & ngủ, desk ergonomic.",
                            Price = 2650000.0,
                            RoomNumber = "903",
                            RoomTypeId = 2,
                            Status = "available"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 3,
                            Description = "Đang có khách — có thể chọn ngày khác.",
                            Price = 2750000.0,
                            RoomNumber = "904",
                            RoomTypeId = 2,
                            Status = "occupied"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 3,
                            Description = "Lan can kính, view bình minh và resort pool.",
                            Price = 4200000.0,
                            RoomNumber = "1201",
                            RoomTypeId = 3,
                            Status = "available"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            Description = "Ban công lớn, outdoor lounge nhỏ.",
                            Price = 4350000.0,
                            RoomNumber = "1205",
                            RoomTypeId = 3,
                            Status = "available"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            Description = "Living riêng, Nespresso bar, bồn tắm freestanding.",
                            Price = 5890000.0,
                            RoomNumber = "1508",
                            RoomTypeId = 4,
                            Status = "available"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            Description = "Corner suite hai hướng cửa sổ, mood lighting.",
                            Price = 6100000.0,
                            RoomNumber = "1510",
                            RoomTypeId = 4,
                            Status = "available"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 5,
                            Description = "Twin + queen, vách di động, kệ đồ chơi cho trẻ.",
                            Price = 3490000.0,
                            RoomNumber = "608",
                            RoomTypeId = 5,
                            Status = "available"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 6,
                            Description = "Duplex penthouse, jacuzzi và lounge riêng.",
                            Price = 8990000.0,
                            RoomNumber = "1801",
                            RoomTypeId = 6,
                            Status = "available"
                        });
                });

            modelBuilder.Entity("backend.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("room_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phòng tiêu chuẩn tối giản, đủ tiện nghi cho công tác ngắn.",
                            Name = "Phòng Tiêu Chuẩn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Không gian rộng hơn, khu vực làm việc và sofa nhỏ.",
                            Name = "Phòng Cao Cấp"
                        },
                        new
                        {
                            Id = 3,
                            Description = "View biển panorama, ban công riêng.",
                            Name = "Phòng Hướng Biển"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Suite phòng khách riêng, bồn tắm và minibar cao cấp.",
                            Name = "Phòng Suite Sang Trọng"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hai phòng ngủ thông nhau, lý tưởng cho gia đình.",
                            Name = "Phòng Gia Đình"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Penthouse tầng cao, dịch vụ concierge riêng.",
                            Name = "Phòng VIP Thượng Hạng"
                        });
                });

            modelBuilder.Entity("backend.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "06:30–10:30 tại nhà hàng The Pearl.",
                            Name = "Buffet sáng quốc tế",
                            Price = 350000.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Massage body & aromatic oil.",
                            Name = "Spa relaxation 60 phút",
                            Price = 950000.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Xe limousine 7 chỗ, đặt trước 4h.",
                            Name = "Đưa đón sân bay (một chiều)",
                            Price = 480000.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nhận trong ngày tùy khối lượng.",
                            Name = "Giặt ủi express",
                            Price = 150000.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Đồ uống & snack refill theo menu.",
                            Name = "Minibar package",
                            Price = 420000.0
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = "2026-01-01 00:00:00",
                            Email = "admin@example.com",
                            IsActive = 1,
                            Name = "Admin",
                            Password = "$2a$11$5PlfRU/P6ZR714i/xz54GuBxv3EqpdI.lBNGq9kwsTRo3Tq7i3X0e",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Payment", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.HasOne("backend.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("backend.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
